CRATE_SUFFIX = {
    'ID_SUFFIX': '_CRATE_ID',
    'NAME_SUFFIX': '_CRATE_NAME',
    'SHORT_NAME_SUFFIX': '_CRATE_SHORT_NAME',
    'HISTOGRAM_ID_SUFFIX': '_ITEM_ORDERS_HISTOGRAM_ID',
    'PRICE_OVERVIEW_SUFFIX': '_PRICE_OVERVIEW_NAME'
}

SUMMARY_REGEX = "(?<=<span class=\"market_commodity_orders_header_promote\">)[0-9]+(?=</span>)"

ORANGE_COLOR = 'fcd6b4'
BLUE_COLOR = 'b7dee8'
RED_COLOR = 'ffc7ce'
YELLOW_COLOR = 'ffeb9c'
GREEN_COLOR = 'c6efce'

BUY_HISTOGRAM_COLOR = RED_COLOR
SELL_HISTOGRAM_COLOR = GREEN_COLOR
VOLUME_HISTOGRAM_COLOR = BLUE_COLOR
PRICE_HISTOGRAM_COLOR = YELLOW_COLOR
