CRATE_SUFFIX = {
    'ID_SUFFIX': '_CRATE_ID',
    'NAME_SUFFIX': '_CRATE_NAME',
    'SHORT_NAME_SUFFIX': '_CRATE_SHORT_NAME',
    'HISTOGRAM_ID_SUFFIX': '_ITEM_ORDERS_HISTOGRAM_ID',
    'PRICE_OVERVIEW_SUFFIX': '_PRICE_OVERVIEW_NAME'
}
