REQUIRED_CASED = (
    'BREAKOUT',
    'CHROMA',
    'CHROMA_2',
    'CHROMA_3',
    'CLUTCH',
    'CS20',
    'DANGER_ZONE',
    'FALCHION',
    'GAMMA',
    'GAMMA_2',
    'GLOVE',
    'HORIZON',
    'PHOENIX',
    'PRISMA',
    'PRISMA_2',
    'REVOLVER',
    'SHADOW',
    # 'SHATTERED_WEB',
    'SPECTRUM',
    'SPECTRUM_2',
    'WILDFIRE'
)
