# common
HEADER_ROW_INDEX = 1

DATE_COLUMN_INDEX = 1
STATUS_COLUMN_INDEX = 2

DATE_COLUMN_NAME = 'Date'
STATUS_COLUMN_NAME = '?'

DATE_COLUMN_WIDTH = 20
STATUS_COLUMN_WIDTH = 3

# overview
VALUE_COLUMN_WIDTH = 12

# histogram

PRICE_COLUMN_INDEX = 3
VOLUME_COLUMN_INDEX = 4
BUY_COLUMN_INDEX = 5
SELL_COLUMN_INDEX = 6
ORDERS_COLUMN_START_INDEX = 7

PRICE_COLUMN_NAME = 'Price'
VOLUME_COLUMN_NAME = 'Volume'
BUY_COLUMN_NAME = 'Buy orders'
SELL_COLUMN_NAME = 'Sell orders'

PRICE_COLUMN_WIDTH = 12
VOLUME_COLUMN_WIDTH = 12
BUY_COLUMN_WIDTH = 12
SELL_COLUMN_WIDTH = 12

ORDERS_COLUMN_WIDTH = 8

