DATE_COLUMN = 'A'
DATE_COLUMN_INDEX = 1
DATE_COLUMN_NAME = 'Date'

# overview


# histogram
# VOLUME_COLUMN = 'B'
# BUY_COLUMN = 'C'
# SELL_COLUMN = 'D'

PRICE_COLUMN_INDEX = 2
VOLUME_COLUMN_INDEX = 3
BUY_COLUMN_INDEX = 4
SELL_COLUMN_INDEX = 5

ORDERS_COLUMN_START_INDEX = 6

PRICE_COLUMN_NAME = 'Price'
VOLUME_COLUMN_NAME = 'Volume'
BUY_COLUMN_NAME = 'Buy orders'
SELL_COLUMN_NAME = 'Sell orders'
