DATE_COLUMN_LETTER = 'A'
DATE_COLUMN_INDEX = 1
DATE_COLUMN_NAME = 'Date'

# STATUS_COLUMN_LETTER = 'B'
STATUS_COLUMN_INDEX = 2
STATUS_COLUMN_NAME = '?'

# overview


# histogram
# VOLUME_COLUMN_LETTER = 'C'
# BUY_COLUMN_LETTER = 'D'
# SELL_COLUMN_LETTER = 'E'

PRICE_COLUMN_INDEX = 3
VOLUME_COLUMN_INDEX = 4
BUY_COLUMN_INDEX = 5
SELL_COLUMN_INDEX = 6

ORDERS_COLUMN_START_INDEX = 7

PRICE_COLUMN_NAME = 'Price'
VOLUME_COLUMN_NAME = 'Volume'
BUY_COLUMN_NAME = 'Buy orders'
SELL_COLUMN_NAME = 'Sell orders'
